language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
install: npm install
script: npm test
notifications:
  email: false
sudo: false
cache:
  directories:
    - "node_modules"
